export const enum AdNetwork {
  GOOGLE_AD_MANAGER = 'GOOGLE_AD_MANAGER',
  ADMOB = 'ADMOB',
  AD_GENERATION = 'AD_GENERATION',
  IRON_SOURCE = 'IRON_SOURCE',
  MAX = 'MAX',
  NIMBUS = 'NIMBUS',
  OTHER = 'OTHER',
}
