name: Publish

on:
  workflow_dispatch:

jobs:
  publish_npm:
    if: "(github.repository == 'adversportTeam/react-native-aps') && (github.event_name == 'workflow_dispatch')"
    name: 'NPM'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Yarn Install
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn install --immutable
      - name: Authenticate with registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Build
        run: yarn build
      - name: Publish Packages
        run: npm publish
