name: Publish

on:
  workflow_dispatch:

jobs:
  publish_npm:
    if: "(github.repository == 'adversportTeam/react-native-aps') && (github.event_name == 'workflow_dispatch')"
    name: 'NPM'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Yarn Install
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn --no-audit --prefer-offline
      - name: Authenticate with registry
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Publish Packages
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
