name: Testing

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'
  push:
    branches:
      - master
    paths-ignore:
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'

jobs:
  jest:
    name: Jest
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v4
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn --no-audit --prefer-offline
      - name: Jest
        run: yarn test:jest-coverage
      - name: Submit Coverage
        # This can fail on timeouts etc, wrap with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./node_modules/.bin/codecov
